// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCefx8qehFkzgumtWbPSczx9-NjlUY6fYU',
    appId: '1:682511286024:web:15b934d7a796439862b6bd',
    messagingSenderId: '682511286024',
    projectId: 'firestore-curd-b4dd2',
    authDomain: 'firestore-curd-b4dd2.firebaseapp.com',
    storageBucket: 'firestore-curd-b4dd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJEIDIKaCk5PYTbigv8rukFaZ6AnvDO1I',
    appId: '1:682511286024:android:668d7571d2e1699262b6bd',
    messagingSenderId: '682511286024',
    projectId: 'firestore-curd-b4dd2',
    storageBucket: 'firestore-curd-b4dd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPW_qbeiPaRrkVGHWFEtDxQfB_E1sLGeE',
    appId: '1:682511286024:ios:e553a8dda44fffca62b6bd',
    messagingSenderId: '682511286024',
    projectId: 'firestore-curd-b4dd2',
    storageBucket: 'firestore-curd-b4dd2.appspot.com',
    iosClientId: '682511286024-hg4s7vjceg6da032nqeekekikcftllkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreCurd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPW_qbeiPaRrkVGHWFEtDxQfB_E1sLGeE',
    appId: '1:682511286024:ios:e553a8dda44fffca62b6bd',
    messagingSenderId: '682511286024',
    projectId: 'firestore-curd-b4dd2',
    storageBucket: 'firestore-curd-b4dd2.appspot.com',
    iosClientId: '682511286024-hg4s7vjceg6da032nqeekekikcftllkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreCurd',
  );
}
